#!/usr/bin/env bash
# sts-creds.sh — Compute MFA TOTP from a base32 secret file and call
# `aws sts assume-role`. Writes the resulting AWS_* exports to --out.
#
# Usage:
#   scripts/sts-creds.sh \
#     --profile lab_kevin \
#     --role-arn arn:aws:iam::404906229455:role/lab_kevin_access \
#     --mfa-arn arn:aws:iam::404906229455:mfa/Kevin-MFA \
#     --mfa-secret-file ~/.okd/mfa-secret \
#     --duration 43200 \
#     --out ~/.okd/sts-env
set -euo pipefail

# shellcheck source=_lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"

usage() {
  cat >&2 <<EOF
Usage: $(basename "$0") --profile <name> --role-arn <arn> --mfa-arn <arn> \\
                       --mfa-secret-file <path> [--duration <seconds>] \\
                       --out <file> [--dry-run]

Defaults: --duration 43200

After completion, run:  source <file>
EOF
  exit 2
}

main() {
  local args=()
  mapfile -t args < <(parse_dry_run_flag "$@")
  set -- "${args[@]+"${args[@]}"}"

  local profile="" role_arn="" mfa_arn="" secret_file="" out_file=""
  local duration=43200

  while (($# > 0)); do
    case "$1" in
      --profile)         profile="${2:?}";      shift 2 ;;
      --role-arn)        role_arn="${2:?}";     shift 2 ;;
      --mfa-arn)         mfa_arn="${2:?}";      shift 2 ;;
      --mfa-secret-file) secret_file="${2:?}";  shift 2 ;;
      --duration)        duration="${2:?}";     shift 2 ;;
      --out)             out_file="${2:?}";     shift 2 ;;
      -h|--help)         usage ;;
      *) log_error "Unknown arg: $1"; usage ;;
    esac
  done

  for required in profile role_arn mfa_arn secret_file out_file; do
    if [[ -z "${!required}" ]]; then
      local flag="${required//_/-}"
      [[ "$flag" == "out-file" ]] && flag="out"
      log_error "--$flag is required"
      usage
    fi
  done

  require_cmd aws jq oathtool

  [[ -r "$secret_file" ]] || { log_error "MFA secret file not readable: $secret_file"; exit 1; }

  local secret
  secret="$(tr -d '[:space:]' <"$secret_file")"
  [[ -n "$secret" ]] || { log_error "MFA secret file is empty: $secret_file"; exit 1; }

  log_info "Computing TOTP from $secret_file"
  local mfa_code
  if [[ "$DRY_RUN" == "true" ]]; then
    mfa_code="000000"
    log_info "[DRY-RUN] would compute TOTP via oathtool"
  else
    mfa_code="$(oathtool --base32 --totp "$secret")"
  fi
  [[ "$mfa_code" =~ ^[0-9]{6}$ ]] || { log_error "Invalid TOTP code generated: $mfa_code"; exit 1; }

  local sts_response
  log_info "Calling aws sts assume-role (profile=$profile duration=${duration}s)"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "[DRY-RUN] aws sts assume-role --role-arn $role_arn --serial-number $mfa_arn --token-code <REDACTED> --duration-seconds $duration --profile $profile"
    sts_response='{"Credentials":{"AccessKeyId":"DRYRUN","SecretAccessKey":"DRYRUN","SessionToken":"DRYRUN","Expiration":"1970-01-01T00:00:00Z"}}'
  else
    sts_response="$(
      aws sts assume-role \
        --role-arn "$role_arn" \
        --role-session-name "okd-deploy-$(date +%s)" \
        --serial-number "$mfa_arn" \
        --token-code "$mfa_code" \
        --duration-seconds "$duration" \
        --output json \
        --profile "$profile"
    )" || { log_error "aws sts assume-role failed"; exit 1; }
  fi

  local ak sk token expiration
  ak="$(jq -r '.Credentials.AccessKeyId'     <<<"$sts_response")"
  sk="$(jq -r '.Credentials.SecretAccessKey' <<<"$sts_response")"
  token="$(jq -r '.Credentials.SessionToken' <<<"$sts_response")"
  expiration="$(jq -r '.Credentials.Expiration' <<<"$sts_response")"

  for v in ak sk token; do
    [[ -n "${!v}" && "${!v}" != "null" ]] || { log_error "Missing $v in STS response"; exit 1; }
  done

  mkdir -p "$(dirname "$out_file")"
  local tmp
  tmp="$(mktemp)"
  cat >"$tmp" <<EOF
# Generated by sts-creds.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Expires: $expiration
export AWS_ACCESS_KEY_ID='$ak'
export AWS_SECRET_ACCESS_KEY='$sk'
export AWS_SESSION_TOKEN='$token'
export AWS_STS_EXPIRATION='$expiration'
EOF
  chmod 600 "$tmp"
  mv "$tmp" "$out_file"

  log_ok "STS credentials written to $out_file (expires $expiration)"
  log_info "Activate with:  source $out_file"
}

main "$@"
